use super::message::MessageEntity;

pub enum InputMedia {
    Photo {
        r#type: String,
        media: String,
        caption: Option<String>,
        parse_mode: Option<String>,
        caption_entities: Option<Vec<MessageEntity>>,
        has_spoilers: Option<bool>,
    },
    Document {
        r#type: String,
        media: String,
        caption: Option<String>,
        parse_mode: Option<String>,
        caption_entities: Option<Vec<MessageEntity>>,
        disable_content_type_detection: Option<bool>,
    },
    Audio {
        r#type: String,
        media: String,
        caption: Option<String>,
        parse_mode: Option<String>,
        caption_entities: Option<Vec<MessageEntity>>,
        duration: Option<i32>,
        performer: Option<String>,
        title: Option<String>,
    },
    Animation {
        r#type: String,
        media: String,
        caption: Option<String>,
        parse_mode: Option<String>,
        caption_entities: Option<Vec<MessageEntity>>,
        width: Option<i32>,
        height: Option<i32>,
        duration: Option<i32>,
        has_spoilers: Option<bool>,
    },
    Video {
        r#type: String,
        media: String,
        caption: Option<String>,
        parse_mode: Option<String>,
        caption_entities: Option<Vec<MessageEntity>>,
        width: Option<i32>,
        height: Option<i32>,
        duration: Option<i32>,
        supports_streaming: Option<bool>,
        has_spoilers: Option<bool>,
    },
}
